### ISSUE TITLE
Record to other formats

### ISSUE THREAD

**Issue by sohussain** [KinectEx/KinectEx#4]
Is there any way to convert the output of the DVR to something more standard? Like a .avi or .mp4 file?

**Comment by ptyork** [comment]
I'd been meaning to add this capability.

Grab the latest push. I've added a little utility to convert the kdvr file to a video file using ffmpeg. Super simple. Just make sure the kdvr2video.exe and ffmpeg.exe files are located in the same folder (just build the solution and run from the bin folder, but if you want to move the exe's just keep them together) Then just run:

kdvr2video [kdvrfile] [videofile]

e.g.,

kdvr2video c:\users\paul\test.kdvr c:\users\paul\test.mp4

Wait a minute or two and your mp4 file should be ready to go.

**Comment by sohussain** [comment]
Thanks!
